######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 15 07:31:30 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += server.h
SOURCES += main.cpp server.cpp
