#############################################################################
# Makefile for building: examples
# Generated by qmake (2.01a) (Qt 4.7.1) on: Thu Sep 12 15:01:32 2013
# Project:  examples.pro
# Template: subdirs
# Command: /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/bin/qmake -spec ../mkspecs/qws/linux-arm-g++ -o Makefile examples.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-network \
		sub-statemachine \
		sub-threads \
		sub-xml \
		sub-animation \
		sub-desktop \
		sub-dialogs \
		sub-draganddrop \
		sub-effects \
		sub-graphicsview \
		sub-ipc \
		sub-itemviews \
		sub-layouts \
		sub-linguist \
		sub-mainwindows \
		sub-painting \
		sub-richtext \
		sub-sql \
		sub-tools \
		sub-tutorials \
		sub-widgets \
		sub-uitools \
		sub-touch \
		sub-gestures \
		sub-script \
		sub-qws \
		sub-declarative

network/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) network/ || $(MKDIR) network/ 
	cd network/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/network/network.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-network-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) network/ || $(MKDIR) network/ 
	cd network/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/network/network.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-network: network/$(MAKEFILE) FORCE
	cd network/ && $(MAKE) -f $(MAKEFILE)
sub-network-make_default: network/$(MAKEFILE) FORCE
	cd network/ && $(MAKE) -f $(MAKEFILE) 
sub-network-make_first: network/$(MAKEFILE) FORCE
	cd network/ && $(MAKE) -f $(MAKEFILE) first
sub-network-all: network/$(MAKEFILE) FORCE
	cd network/ && $(MAKE) -f $(MAKEFILE) all
sub-network-clean: network/$(MAKEFILE) FORCE
	cd network/ && $(MAKE) -f $(MAKEFILE) clean
sub-network-distclean: network/$(MAKEFILE) FORCE
	cd network/ && $(MAKE) -f $(MAKEFILE) distclean
sub-network-install_subtargets: network/$(MAKEFILE) FORCE
	cd network/ && $(MAKE) -f $(MAKEFILE) install
sub-network-uninstall_subtargets: network/$(MAKEFILE) FORCE
	cd network/ && $(MAKE) -f $(MAKEFILE) uninstall
statemachine/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) statemachine/ || $(MKDIR) statemachine/ 
	cd statemachine/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/statemachine/statemachine.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-statemachine-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) statemachine/ || $(MKDIR) statemachine/ 
	cd statemachine/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/statemachine/statemachine.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-statemachine: statemachine/$(MAKEFILE) FORCE
	cd statemachine/ && $(MAKE) -f $(MAKEFILE)
sub-statemachine-make_default: statemachine/$(MAKEFILE) FORCE
	cd statemachine/ && $(MAKE) -f $(MAKEFILE) 
sub-statemachine-make_first: statemachine/$(MAKEFILE) FORCE
	cd statemachine/ && $(MAKE) -f $(MAKEFILE) first
sub-statemachine-all: statemachine/$(MAKEFILE) FORCE
	cd statemachine/ && $(MAKE) -f $(MAKEFILE) all
sub-statemachine-clean: statemachine/$(MAKEFILE) FORCE
	cd statemachine/ && $(MAKE) -f $(MAKEFILE) clean
sub-statemachine-distclean: statemachine/$(MAKEFILE) FORCE
	cd statemachine/ && $(MAKE) -f $(MAKEFILE) distclean
sub-statemachine-install_subtargets: statemachine/$(MAKEFILE) FORCE
	cd statemachine/ && $(MAKE) -f $(MAKEFILE) install
sub-statemachine-uninstall_subtargets: statemachine/$(MAKEFILE) FORCE
	cd statemachine/ && $(MAKE) -f $(MAKEFILE) uninstall
threads/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) threads/ || $(MKDIR) threads/ 
	cd threads/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/threads/threads.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-threads-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) threads/ || $(MKDIR) threads/ 
	cd threads/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/threads/threads.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-threads: threads/$(MAKEFILE) FORCE
	cd threads/ && $(MAKE) -f $(MAKEFILE)
sub-threads-make_default: threads/$(MAKEFILE) FORCE
	cd threads/ && $(MAKE) -f $(MAKEFILE) 
sub-threads-make_first: threads/$(MAKEFILE) FORCE
	cd threads/ && $(MAKE) -f $(MAKEFILE) first
sub-threads-all: threads/$(MAKEFILE) FORCE
	cd threads/ && $(MAKE) -f $(MAKEFILE) all
sub-threads-clean: threads/$(MAKEFILE) FORCE
	cd threads/ && $(MAKE) -f $(MAKEFILE) clean
sub-threads-distclean: threads/$(MAKEFILE) FORCE
	cd threads/ && $(MAKE) -f $(MAKEFILE) distclean
sub-threads-install_subtargets: threads/$(MAKEFILE) FORCE
	cd threads/ && $(MAKE) -f $(MAKEFILE) install
sub-threads-uninstall_subtargets: threads/$(MAKEFILE) FORCE
	cd threads/ && $(MAKE) -f $(MAKEFILE) uninstall
xml/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) xml/ || $(MKDIR) xml/ 
	cd xml/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/xml/xml.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-xml-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) xml/ || $(MKDIR) xml/ 
	cd xml/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/xml/xml.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-xml: xml/$(MAKEFILE) FORCE
	cd xml/ && $(MAKE) -f $(MAKEFILE)
sub-xml-make_default: xml/$(MAKEFILE) FORCE
	cd xml/ && $(MAKE) -f $(MAKEFILE) 
sub-xml-make_first: xml/$(MAKEFILE) FORCE
	cd xml/ && $(MAKE) -f $(MAKEFILE) first
sub-xml-all: xml/$(MAKEFILE) FORCE
	cd xml/ && $(MAKE) -f $(MAKEFILE) all
sub-xml-clean: xml/$(MAKEFILE) FORCE
	cd xml/ && $(MAKE) -f $(MAKEFILE) clean
sub-xml-distclean: xml/$(MAKEFILE) FORCE
	cd xml/ && $(MAKE) -f $(MAKEFILE) distclean
sub-xml-install_subtargets: xml/$(MAKEFILE) FORCE
	cd xml/ && $(MAKE) -f $(MAKEFILE) install
sub-xml-uninstall_subtargets: xml/$(MAKEFILE) FORCE
	cd xml/ && $(MAKE) -f $(MAKEFILE) uninstall
animation/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) animation/ || $(MKDIR) animation/ 
	cd animation/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/animation/animation.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-animation-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) animation/ || $(MKDIR) animation/ 
	cd animation/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/animation/animation.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-animation: animation/$(MAKEFILE) FORCE
	cd animation/ && $(MAKE) -f $(MAKEFILE)
sub-animation-make_default: animation/$(MAKEFILE) FORCE
	cd animation/ && $(MAKE) -f $(MAKEFILE) 
sub-animation-make_first: animation/$(MAKEFILE) FORCE
	cd animation/ && $(MAKE) -f $(MAKEFILE) first
sub-animation-all: animation/$(MAKEFILE) FORCE
	cd animation/ && $(MAKE) -f $(MAKEFILE) all
sub-animation-clean: animation/$(MAKEFILE) FORCE
	cd animation/ && $(MAKE) -f $(MAKEFILE) clean
sub-animation-distclean: animation/$(MAKEFILE) FORCE
	cd animation/ && $(MAKE) -f $(MAKEFILE) distclean
sub-animation-install_subtargets: animation/$(MAKEFILE) FORCE
	cd animation/ && $(MAKE) -f $(MAKEFILE) install
sub-animation-uninstall_subtargets: animation/$(MAKEFILE) FORCE
	cd animation/ && $(MAKE) -f $(MAKEFILE) uninstall
desktop/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) desktop/ || $(MKDIR) desktop/ 
	cd desktop/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/desktop/desktop.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-desktop-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) desktop/ || $(MKDIR) desktop/ 
	cd desktop/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/desktop/desktop.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-desktop: desktop/$(MAKEFILE) FORCE
	cd desktop/ && $(MAKE) -f $(MAKEFILE)
sub-desktop-make_default: desktop/$(MAKEFILE) FORCE
	cd desktop/ && $(MAKE) -f $(MAKEFILE) 
sub-desktop-make_first: desktop/$(MAKEFILE) FORCE
	cd desktop/ && $(MAKE) -f $(MAKEFILE) first
sub-desktop-all: desktop/$(MAKEFILE) FORCE
	cd desktop/ && $(MAKE) -f $(MAKEFILE) all
sub-desktop-clean: desktop/$(MAKEFILE) FORCE
	cd desktop/ && $(MAKE) -f $(MAKEFILE) clean
sub-desktop-distclean: desktop/$(MAKEFILE) FORCE
	cd desktop/ && $(MAKE) -f $(MAKEFILE) distclean
sub-desktop-install_subtargets: desktop/$(MAKEFILE) FORCE
	cd desktop/ && $(MAKE) -f $(MAKEFILE) install
sub-desktop-uninstall_subtargets: desktop/$(MAKEFILE) FORCE
	cd desktop/ && $(MAKE) -f $(MAKEFILE) uninstall
dialogs/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) dialogs/ || $(MKDIR) dialogs/ 
	cd dialogs/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/dialogs/dialogs.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-dialogs-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) dialogs/ || $(MKDIR) dialogs/ 
	cd dialogs/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/dialogs/dialogs.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-dialogs: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE)
sub-dialogs-make_default: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) 
sub-dialogs-make_first: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) first
sub-dialogs-all: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) all
sub-dialogs-clean: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) clean
sub-dialogs-distclean: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) distclean
sub-dialogs-install_subtargets: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) install
sub-dialogs-uninstall_subtargets: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) uninstall
draganddrop/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) draganddrop/ || $(MKDIR) draganddrop/ 
	cd draganddrop/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/draganddrop/draganddrop.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-draganddrop-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) draganddrop/ || $(MKDIR) draganddrop/ 
	cd draganddrop/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/draganddrop/draganddrop.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-draganddrop: draganddrop/$(MAKEFILE) FORCE
	cd draganddrop/ && $(MAKE) -f $(MAKEFILE)
sub-draganddrop-make_default: draganddrop/$(MAKEFILE) FORCE
	cd draganddrop/ && $(MAKE) -f $(MAKEFILE) 
sub-draganddrop-make_first: draganddrop/$(MAKEFILE) FORCE
	cd draganddrop/ && $(MAKE) -f $(MAKEFILE) first
sub-draganddrop-all: draganddrop/$(MAKEFILE) FORCE
	cd draganddrop/ && $(MAKE) -f $(MAKEFILE) all
sub-draganddrop-clean: draganddrop/$(MAKEFILE) FORCE
	cd draganddrop/ && $(MAKE) -f $(MAKEFILE) clean
sub-draganddrop-distclean: draganddrop/$(MAKEFILE) FORCE
	cd draganddrop/ && $(MAKE) -f $(MAKEFILE) distclean
sub-draganddrop-install_subtargets: draganddrop/$(MAKEFILE) FORCE
	cd draganddrop/ && $(MAKE) -f $(MAKEFILE) install
sub-draganddrop-uninstall_subtargets: draganddrop/$(MAKEFILE) FORCE
	cd draganddrop/ && $(MAKE) -f $(MAKEFILE) uninstall
effects/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) effects/ || $(MKDIR) effects/ 
	cd effects/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/effects/effects.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-effects-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) effects/ || $(MKDIR) effects/ 
	cd effects/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/effects/effects.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-effects: effects/$(MAKEFILE) FORCE
	cd effects/ && $(MAKE) -f $(MAKEFILE)
sub-effects-make_default: effects/$(MAKEFILE) FORCE
	cd effects/ && $(MAKE) -f $(MAKEFILE) 
sub-effects-make_first: effects/$(MAKEFILE) FORCE
	cd effects/ && $(MAKE) -f $(MAKEFILE) first
sub-effects-all: effects/$(MAKEFILE) FORCE
	cd effects/ && $(MAKE) -f $(MAKEFILE) all
sub-effects-clean: effects/$(MAKEFILE) FORCE
	cd effects/ && $(MAKE) -f $(MAKEFILE) clean
sub-effects-distclean: effects/$(MAKEFILE) FORCE
	cd effects/ && $(MAKE) -f $(MAKEFILE) distclean
sub-effects-install_subtargets: effects/$(MAKEFILE) FORCE
	cd effects/ && $(MAKE) -f $(MAKEFILE) install
sub-effects-uninstall_subtargets: effects/$(MAKEFILE) FORCE
	cd effects/ && $(MAKE) -f $(MAKEFILE) uninstall
graphicsview/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) graphicsview/ || $(MKDIR) graphicsview/ 
	cd graphicsview/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/graphicsview/graphicsview.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-graphicsview-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) graphicsview/ || $(MKDIR) graphicsview/ 
	cd graphicsview/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/graphicsview/graphicsview.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-graphicsview: graphicsview/$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE)
sub-graphicsview-make_default: graphicsview/$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) 
sub-graphicsview-make_first: graphicsview/$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) first
sub-graphicsview-all: graphicsview/$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) all
sub-graphicsview-clean: graphicsview/$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) clean
sub-graphicsview-distclean: graphicsview/$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) distclean
sub-graphicsview-install_subtargets: graphicsview/$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) install
sub-graphicsview-uninstall_subtargets: graphicsview/$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) uninstall
ipc/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ipc/ || $(MKDIR) ipc/ 
	cd ipc/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/ipc/ipc.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-ipc-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ipc/ || $(MKDIR) ipc/ 
	cd ipc/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/ipc/ipc.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-ipc: ipc/$(MAKEFILE) FORCE
	cd ipc/ && $(MAKE) -f $(MAKEFILE)
sub-ipc-make_default: ipc/$(MAKEFILE) FORCE
	cd ipc/ && $(MAKE) -f $(MAKEFILE) 
sub-ipc-make_first: ipc/$(MAKEFILE) FORCE
	cd ipc/ && $(MAKE) -f $(MAKEFILE) first
sub-ipc-all: ipc/$(MAKEFILE) FORCE
	cd ipc/ && $(MAKE) -f $(MAKEFILE) all
sub-ipc-clean: ipc/$(MAKEFILE) FORCE
	cd ipc/ && $(MAKE) -f $(MAKEFILE) clean
sub-ipc-distclean: ipc/$(MAKEFILE) FORCE
	cd ipc/ && $(MAKE) -f $(MAKEFILE) distclean
sub-ipc-install_subtargets: ipc/$(MAKEFILE) FORCE
	cd ipc/ && $(MAKE) -f $(MAKEFILE) install
sub-ipc-uninstall_subtargets: ipc/$(MAKEFILE) FORCE
	cd ipc/ && $(MAKE) -f $(MAKEFILE) uninstall
itemviews/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) itemviews/ || $(MKDIR) itemviews/ 
	cd itemviews/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/itemviews/itemviews.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-itemviews-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) itemviews/ || $(MKDIR) itemviews/ 
	cd itemviews/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/itemviews/itemviews.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-itemviews: itemviews/$(MAKEFILE) FORCE
	cd itemviews/ && $(MAKE) -f $(MAKEFILE)
sub-itemviews-make_default: itemviews/$(MAKEFILE) FORCE
	cd itemviews/ && $(MAKE) -f $(MAKEFILE) 
sub-itemviews-make_first: itemviews/$(MAKEFILE) FORCE
	cd itemviews/ && $(MAKE) -f $(MAKEFILE) first
sub-itemviews-all: itemviews/$(MAKEFILE) FORCE
	cd itemviews/ && $(MAKE) -f $(MAKEFILE) all
sub-itemviews-clean: itemviews/$(MAKEFILE) FORCE
	cd itemviews/ && $(MAKE) -f $(MAKEFILE) clean
sub-itemviews-distclean: itemviews/$(MAKEFILE) FORCE
	cd itemviews/ && $(MAKE) -f $(MAKEFILE) distclean
sub-itemviews-install_subtargets: itemviews/$(MAKEFILE) FORCE
	cd itemviews/ && $(MAKE) -f $(MAKEFILE) install
sub-itemviews-uninstall_subtargets: itemviews/$(MAKEFILE) FORCE
	cd itemviews/ && $(MAKE) -f $(MAKEFILE) uninstall
layouts/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) layouts/ || $(MKDIR) layouts/ 
	cd layouts/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/layouts/layouts.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-layouts-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) layouts/ || $(MKDIR) layouts/ 
	cd layouts/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/layouts/layouts.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-layouts: layouts/$(MAKEFILE) FORCE
	cd layouts/ && $(MAKE) -f $(MAKEFILE)
sub-layouts-make_default: layouts/$(MAKEFILE) FORCE
	cd layouts/ && $(MAKE) -f $(MAKEFILE) 
sub-layouts-make_first: layouts/$(MAKEFILE) FORCE
	cd layouts/ && $(MAKE) -f $(MAKEFILE) first
sub-layouts-all: layouts/$(MAKEFILE) FORCE
	cd layouts/ && $(MAKE) -f $(MAKEFILE) all
sub-layouts-clean: layouts/$(MAKEFILE) FORCE
	cd layouts/ && $(MAKE) -f $(MAKEFILE) clean
sub-layouts-distclean: layouts/$(MAKEFILE) FORCE
	cd layouts/ && $(MAKE) -f $(MAKEFILE) distclean
sub-layouts-install_subtargets: layouts/$(MAKEFILE) FORCE
	cd layouts/ && $(MAKE) -f $(MAKEFILE) install
sub-layouts-uninstall_subtargets: layouts/$(MAKEFILE) FORCE
	cd layouts/ && $(MAKE) -f $(MAKEFILE) uninstall
linguist/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) linguist/ || $(MKDIR) linguist/ 
	cd linguist/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/linguist/linguist.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-linguist-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) linguist/ || $(MKDIR) linguist/ 
	cd linguist/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/linguist/linguist.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-linguist: linguist/$(MAKEFILE) FORCE
	cd linguist/ && $(MAKE) -f $(MAKEFILE)
sub-linguist-make_default: linguist/$(MAKEFILE) FORCE
	cd linguist/ && $(MAKE) -f $(MAKEFILE) 
sub-linguist-make_first: linguist/$(MAKEFILE) FORCE
	cd linguist/ && $(MAKE) -f $(MAKEFILE) first
sub-linguist-all: linguist/$(MAKEFILE) FORCE
	cd linguist/ && $(MAKE) -f $(MAKEFILE) all
sub-linguist-clean: linguist/$(MAKEFILE) FORCE
	cd linguist/ && $(MAKE) -f $(MAKEFILE) clean
sub-linguist-distclean: linguist/$(MAKEFILE) FORCE
	cd linguist/ && $(MAKE) -f $(MAKEFILE) distclean
sub-linguist-install_subtargets: linguist/$(MAKEFILE) FORCE
	cd linguist/ && $(MAKE) -f $(MAKEFILE) install
sub-linguist-uninstall_subtargets: linguist/$(MAKEFILE) FORCE
	cd linguist/ && $(MAKE) -f $(MAKEFILE) uninstall
mainwindows/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) mainwindows/ || $(MKDIR) mainwindows/ 
	cd mainwindows/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/mainwindows/mainwindows.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-mainwindows-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) mainwindows/ || $(MKDIR) mainwindows/ 
	cd mainwindows/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/mainwindows/mainwindows.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-mainwindows: mainwindows/$(MAKEFILE) FORCE
	cd mainwindows/ && $(MAKE) -f $(MAKEFILE)
sub-mainwindows-make_default: mainwindows/$(MAKEFILE) FORCE
	cd mainwindows/ && $(MAKE) -f $(MAKEFILE) 
sub-mainwindows-make_first: mainwindows/$(MAKEFILE) FORCE
	cd mainwindows/ && $(MAKE) -f $(MAKEFILE) first
sub-mainwindows-all: mainwindows/$(MAKEFILE) FORCE
	cd mainwindows/ && $(MAKE) -f $(MAKEFILE) all
sub-mainwindows-clean: mainwindows/$(MAKEFILE) FORCE
	cd mainwindows/ && $(MAKE) -f $(MAKEFILE) clean
sub-mainwindows-distclean: mainwindows/$(MAKEFILE) FORCE
	cd mainwindows/ && $(MAKE) -f $(MAKEFILE) distclean
sub-mainwindows-install_subtargets: mainwindows/$(MAKEFILE) FORCE
	cd mainwindows/ && $(MAKE) -f $(MAKEFILE) install
sub-mainwindows-uninstall_subtargets: mainwindows/$(MAKEFILE) FORCE
	cd mainwindows/ && $(MAKE) -f $(MAKEFILE) uninstall
painting/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) painting/ || $(MKDIR) painting/ 
	cd painting/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/painting/painting.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-painting-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) painting/ || $(MKDIR) painting/ 
	cd painting/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/painting/painting.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-painting: painting/$(MAKEFILE) FORCE
	cd painting/ && $(MAKE) -f $(MAKEFILE)
sub-painting-make_default: painting/$(MAKEFILE) FORCE
	cd painting/ && $(MAKE) -f $(MAKEFILE) 
sub-painting-make_first: painting/$(MAKEFILE) FORCE
	cd painting/ && $(MAKE) -f $(MAKEFILE) first
sub-painting-all: painting/$(MAKEFILE) FORCE
	cd painting/ && $(MAKE) -f $(MAKEFILE) all
sub-painting-clean: painting/$(MAKEFILE) FORCE
	cd painting/ && $(MAKE) -f $(MAKEFILE) clean
sub-painting-distclean: painting/$(MAKEFILE) FORCE
	cd painting/ && $(MAKE) -f $(MAKEFILE) distclean
sub-painting-install_subtargets: painting/$(MAKEFILE) FORCE
	cd painting/ && $(MAKE) -f $(MAKEFILE) install
sub-painting-uninstall_subtargets: painting/$(MAKEFILE) FORCE
	cd painting/ && $(MAKE) -f $(MAKEFILE) uninstall
richtext/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) richtext/ || $(MKDIR) richtext/ 
	cd richtext/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/richtext/richtext.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-richtext-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) richtext/ || $(MKDIR) richtext/ 
	cd richtext/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/richtext/richtext.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-richtext: richtext/$(MAKEFILE) FORCE
	cd richtext/ && $(MAKE) -f $(MAKEFILE)
sub-richtext-make_default: richtext/$(MAKEFILE) FORCE
	cd richtext/ && $(MAKE) -f $(MAKEFILE) 
sub-richtext-make_first: richtext/$(MAKEFILE) FORCE
	cd richtext/ && $(MAKE) -f $(MAKEFILE) first
sub-richtext-all: richtext/$(MAKEFILE) FORCE
	cd richtext/ && $(MAKE) -f $(MAKEFILE) all
sub-richtext-clean: richtext/$(MAKEFILE) FORCE
	cd richtext/ && $(MAKE) -f $(MAKEFILE) clean
sub-richtext-distclean: richtext/$(MAKEFILE) FORCE
	cd richtext/ && $(MAKE) -f $(MAKEFILE) distclean
sub-richtext-install_subtargets: richtext/$(MAKEFILE) FORCE
	cd richtext/ && $(MAKE) -f $(MAKEFILE) install
sub-richtext-uninstall_subtargets: richtext/$(MAKEFILE) FORCE
	cd richtext/ && $(MAKE) -f $(MAKEFILE) uninstall
sql/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) sql/ || $(MKDIR) sql/ 
	cd sql/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/sql/sql.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-sql-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) sql/ || $(MKDIR) sql/ 
	cd sql/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/sql/sql.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-sql: sql/$(MAKEFILE) FORCE
	cd sql/ && $(MAKE) -f $(MAKEFILE)
sub-sql-make_default: sql/$(MAKEFILE) FORCE
	cd sql/ && $(MAKE) -f $(MAKEFILE) 
sub-sql-make_first: sql/$(MAKEFILE) FORCE
	cd sql/ && $(MAKE) -f $(MAKEFILE) first
sub-sql-all: sql/$(MAKEFILE) FORCE
	cd sql/ && $(MAKE) -f $(MAKEFILE) all
sub-sql-clean: sql/$(MAKEFILE) FORCE
	cd sql/ && $(MAKE) -f $(MAKEFILE) clean
sub-sql-distclean: sql/$(MAKEFILE) FORCE
	cd sql/ && $(MAKE) -f $(MAKEFILE) distclean
sub-sql-install_subtargets: sql/$(MAKEFILE) FORCE
	cd sql/ && $(MAKE) -f $(MAKEFILE) install
sub-sql-uninstall_subtargets: sql/$(MAKEFILE) FORCE
	cd sql/ && $(MAKE) -f $(MAKEFILE) uninstall
tools/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tools/ || $(MKDIR) tools/ 
	cd tools/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/tools/tools.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-tools-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tools/ || $(MKDIR) tools/ 
	cd tools/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/tools/tools.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-tools: tools/$(MAKEFILE) FORCE
	cd tools/ && $(MAKE) -f $(MAKEFILE)
sub-tools-make_default: tools/$(MAKEFILE) FORCE
	cd tools/ && $(MAKE) -f $(MAKEFILE) 
sub-tools-make_first: tools/$(MAKEFILE) FORCE
	cd tools/ && $(MAKE) -f $(MAKEFILE) first
sub-tools-all: tools/$(MAKEFILE) FORCE
	cd tools/ && $(MAKE) -f $(MAKEFILE) all
sub-tools-clean: tools/$(MAKEFILE) FORCE
	cd tools/ && $(MAKE) -f $(MAKEFILE) clean
sub-tools-distclean: tools/$(MAKEFILE) FORCE
	cd tools/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tools-install_subtargets: tools/$(MAKEFILE) FORCE
	cd tools/ && $(MAKE) -f $(MAKEFILE) install
sub-tools-uninstall_subtargets: tools/$(MAKEFILE) FORCE
	cd tools/ && $(MAKE) -f $(MAKEFILE) uninstall
tutorials/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tutorials/ || $(MKDIR) tutorials/ 
	cd tutorials/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/tutorials/tutorials.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-tutorials-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tutorials/ || $(MKDIR) tutorials/ 
	cd tutorials/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/tutorials/tutorials.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-tutorials: tutorials/$(MAKEFILE) FORCE
	cd tutorials/ && $(MAKE) -f $(MAKEFILE)
sub-tutorials-make_default: tutorials/$(MAKEFILE) FORCE
	cd tutorials/ && $(MAKE) -f $(MAKEFILE) 
sub-tutorials-make_first: tutorials/$(MAKEFILE) FORCE
	cd tutorials/ && $(MAKE) -f $(MAKEFILE) first
sub-tutorials-all: tutorials/$(MAKEFILE) FORCE
	cd tutorials/ && $(MAKE) -f $(MAKEFILE) all
sub-tutorials-clean: tutorials/$(MAKEFILE) FORCE
	cd tutorials/ && $(MAKE) -f $(MAKEFILE) clean
sub-tutorials-distclean: tutorials/$(MAKEFILE) FORCE
	cd tutorials/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tutorials-install_subtargets: tutorials/$(MAKEFILE) FORCE
	cd tutorials/ && $(MAKE) -f $(MAKEFILE) install
sub-tutorials-uninstall_subtargets: tutorials/$(MAKEFILE) FORCE
	cd tutorials/ && $(MAKE) -f $(MAKEFILE) uninstall
widgets/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) widgets/ || $(MKDIR) widgets/ 
	cd widgets/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/widgets/widgets.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-widgets-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) widgets/ || $(MKDIR) widgets/ 
	cd widgets/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/widgets/widgets.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-widgets: widgets/$(MAKEFILE) FORCE
	cd widgets/ && $(MAKE) -f $(MAKEFILE)
sub-widgets-make_default: widgets/$(MAKEFILE) FORCE
	cd widgets/ && $(MAKE) -f $(MAKEFILE) 
sub-widgets-make_first: widgets/$(MAKEFILE) FORCE
	cd widgets/ && $(MAKE) -f $(MAKEFILE) first
sub-widgets-all: widgets/$(MAKEFILE) FORCE
	cd widgets/ && $(MAKE) -f $(MAKEFILE) all
sub-widgets-clean: widgets/$(MAKEFILE) FORCE
	cd widgets/ && $(MAKE) -f $(MAKEFILE) clean
sub-widgets-distclean: widgets/$(MAKEFILE) FORCE
	cd widgets/ && $(MAKE) -f $(MAKEFILE) distclean
sub-widgets-install_subtargets: widgets/$(MAKEFILE) FORCE
	cd widgets/ && $(MAKE) -f $(MAKEFILE) install
sub-widgets-uninstall_subtargets: widgets/$(MAKEFILE) FORCE
	cd widgets/ && $(MAKE) -f $(MAKEFILE) uninstall
uitools/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) uitools/ || $(MKDIR) uitools/ 
	cd uitools/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/uitools/uitools.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-uitools-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) uitools/ || $(MKDIR) uitools/ 
	cd uitools/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/uitools/uitools.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-uitools: uitools/$(MAKEFILE) FORCE
	cd uitools/ && $(MAKE) -f $(MAKEFILE)
sub-uitools-make_default: uitools/$(MAKEFILE) FORCE
	cd uitools/ && $(MAKE) -f $(MAKEFILE) 
sub-uitools-make_first: uitools/$(MAKEFILE) FORCE
	cd uitools/ && $(MAKE) -f $(MAKEFILE) first
sub-uitools-all: uitools/$(MAKEFILE) FORCE
	cd uitools/ && $(MAKE) -f $(MAKEFILE) all
sub-uitools-clean: uitools/$(MAKEFILE) FORCE
	cd uitools/ && $(MAKE) -f $(MAKEFILE) clean
sub-uitools-distclean: uitools/$(MAKEFILE) FORCE
	cd uitools/ && $(MAKE) -f $(MAKEFILE) distclean
sub-uitools-install_subtargets: uitools/$(MAKEFILE) FORCE
	cd uitools/ && $(MAKE) -f $(MAKEFILE) install
sub-uitools-uninstall_subtargets: uitools/$(MAKEFILE) FORCE
	cd uitools/ && $(MAKE) -f $(MAKEFILE) uninstall
touch/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) touch/ || $(MKDIR) touch/ 
	cd touch/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/touch/touch.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-touch-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) touch/ || $(MKDIR) touch/ 
	cd touch/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/touch/touch.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-touch: touch/$(MAKEFILE) FORCE
	cd touch/ && $(MAKE) -f $(MAKEFILE)
sub-touch-make_default: touch/$(MAKEFILE) FORCE
	cd touch/ && $(MAKE) -f $(MAKEFILE) 
sub-touch-make_first: touch/$(MAKEFILE) FORCE
	cd touch/ && $(MAKE) -f $(MAKEFILE) first
sub-touch-all: touch/$(MAKEFILE) FORCE
	cd touch/ && $(MAKE) -f $(MAKEFILE) all
sub-touch-clean: touch/$(MAKEFILE) FORCE
	cd touch/ && $(MAKE) -f $(MAKEFILE) clean
sub-touch-distclean: touch/$(MAKEFILE) FORCE
	cd touch/ && $(MAKE) -f $(MAKEFILE) distclean
sub-touch-install_subtargets: touch/$(MAKEFILE) FORCE
	cd touch/ && $(MAKE) -f $(MAKEFILE) install
sub-touch-uninstall_subtargets: touch/$(MAKEFILE) FORCE
	cd touch/ && $(MAKE) -f $(MAKEFILE) uninstall
gestures/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) gestures/ || $(MKDIR) gestures/ 
	cd gestures/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/gestures/gestures.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-gestures-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) gestures/ || $(MKDIR) gestures/ 
	cd gestures/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/gestures/gestures.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-gestures: gestures/$(MAKEFILE) FORCE
	cd gestures/ && $(MAKE) -f $(MAKEFILE)
sub-gestures-make_default: gestures/$(MAKEFILE) FORCE
	cd gestures/ && $(MAKE) -f $(MAKEFILE) 
sub-gestures-make_first: gestures/$(MAKEFILE) FORCE
	cd gestures/ && $(MAKE) -f $(MAKEFILE) first
sub-gestures-all: gestures/$(MAKEFILE) FORCE
	cd gestures/ && $(MAKE) -f $(MAKEFILE) all
sub-gestures-clean: gestures/$(MAKEFILE) FORCE
	cd gestures/ && $(MAKE) -f $(MAKEFILE) clean
sub-gestures-distclean: gestures/$(MAKEFILE) FORCE
	cd gestures/ && $(MAKE) -f $(MAKEFILE) distclean
sub-gestures-install_subtargets: gestures/$(MAKEFILE) FORCE
	cd gestures/ && $(MAKE) -f $(MAKEFILE) install
sub-gestures-uninstall_subtargets: gestures/$(MAKEFILE) FORCE
	cd gestures/ && $(MAKE) -f $(MAKEFILE) uninstall
script/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) script/ || $(MKDIR) script/ 
	cd script/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/script/script.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-script-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) script/ || $(MKDIR) script/ 
	cd script/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/script/script.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-script: script/$(MAKEFILE) FORCE
	cd script/ && $(MAKE) -f $(MAKEFILE)
sub-script-make_default: script/$(MAKEFILE) FORCE
	cd script/ && $(MAKE) -f $(MAKEFILE) 
sub-script-make_first: script/$(MAKEFILE) FORCE
	cd script/ && $(MAKE) -f $(MAKEFILE) first
sub-script-all: script/$(MAKEFILE) FORCE
	cd script/ && $(MAKE) -f $(MAKEFILE) all
sub-script-clean: script/$(MAKEFILE) FORCE
	cd script/ && $(MAKE) -f $(MAKEFILE) clean
sub-script-distclean: script/$(MAKEFILE) FORCE
	cd script/ && $(MAKE) -f $(MAKEFILE) distclean
sub-script-install_subtargets: script/$(MAKEFILE) FORCE
	cd script/ && $(MAKE) -f $(MAKEFILE) install
sub-script-uninstall_subtargets: script/$(MAKEFILE) FORCE
	cd script/ && $(MAKE) -f $(MAKEFILE) uninstall
qws/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qws/ || $(MKDIR) qws/ 
	cd qws/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/qws/qws.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-qws-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qws/ || $(MKDIR) qws/ 
	cd qws/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/qws/qws.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-qws: qws/$(MAKEFILE) FORCE
	cd qws/ && $(MAKE) -f $(MAKEFILE)
sub-qws-make_default: qws/$(MAKEFILE) FORCE
	cd qws/ && $(MAKE) -f $(MAKEFILE) 
sub-qws-make_first: qws/$(MAKEFILE) FORCE
	cd qws/ && $(MAKE) -f $(MAKEFILE) first
sub-qws-all: qws/$(MAKEFILE) FORCE
	cd qws/ && $(MAKE) -f $(MAKEFILE) all
sub-qws-clean: qws/$(MAKEFILE) FORCE
	cd qws/ && $(MAKE) -f $(MAKEFILE) clean
sub-qws-distclean: qws/$(MAKEFILE) FORCE
	cd qws/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qws-install_subtargets: qws/$(MAKEFILE) FORCE
	cd qws/ && $(MAKE) -f $(MAKEFILE) install
sub-qws-uninstall_subtargets: qws/$(MAKEFILE) FORCE
	cd qws/ && $(MAKE) -f $(MAKEFILE) uninstall
declarative/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) declarative/ || $(MKDIR) declarative/ 
	cd declarative/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/declarative/declarative.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-declarative-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) declarative/ || $(MKDIR) declarative/ 
	cd declarative/ && $(QMAKE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/declarative/declarative.pro -spec /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/mkspecs/qws/linux-arm-g++ -o $(MAKEFILE)
sub-declarative: declarative/$(MAKEFILE) FORCE
	cd declarative/ && $(MAKE) -f $(MAKEFILE)
sub-declarative-make_default: declarative/$(MAKEFILE) FORCE
	cd declarative/ && $(MAKE) -f $(MAKEFILE) 
sub-declarative-make_first: declarative/$(MAKEFILE) FORCE
	cd declarative/ && $(MAKE) -f $(MAKEFILE) first
sub-declarative-all: declarative/$(MAKEFILE) FORCE
	cd declarative/ && $(MAKE) -f $(MAKEFILE) all
sub-declarative-clean: declarative/$(MAKEFILE) FORCE
	cd declarative/ && $(MAKE) -f $(MAKEFILE) clean
sub-declarative-distclean: declarative/$(MAKEFILE) FORCE
	cd declarative/ && $(MAKE) -f $(MAKEFILE) distclean
sub-declarative-install_subtargets: declarative/$(MAKEFILE) FORCE
	cd declarative/ && $(MAKE) -f $(MAKEFILE) install
sub-declarative-uninstall_subtargets: declarative/$(MAKEFILE) FORCE
	cd declarative/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: examples.pro ../.qmake.cache ../mkspecs/qws/linux-arm-g++/qmake.conf ../mkspecs/common/g++.conf \
		../mkspecs/common/unix.conf \
		../mkspecs/common/linux.conf \
		../mkspecs/common/qws.conf \
		../mkspecs/features/exclusive_builds.prf \
		../mkspecs/features/default_pre.prf \
		../.qmake.cache \
		../mkspecs/qconfig.pri \
		../mkspecs/features/qt_functions.prf \
		../mkspecs/features/qt_config.prf \
		../mkspecs/features/release.prf \
		../mkspecs/features/default_post.prf \
		../mkspecs/features/unix/dylib.prf \
		../mkspecs/features/unix/largefile.prf \
		../mkspecs/features/dll.prf \
		../mkspecs/features/shared.prf \
		../mkspecs/features/silent.prf \
		../mkspecs/features/warn_on.prf \
		../mkspecs/features/qt.prf \
		../mkspecs/features/unix/thread.prf \
		../mkspecs/features/moc.prf \
		../mkspecs/features/resources.prf \
		../mkspecs/features/uic.prf \
		../mkspecs/features/yacc.prf \
		../mkspecs/features/lex.prf
	$(QMAKE) -spec ../mkspecs/qws/linux-arm-g++ -o Makefile examples.pro
../mkspecs/common/g++.conf:
../mkspecs/common/unix.conf:
../mkspecs/common/linux.conf:
../mkspecs/common/qws.conf:
../mkspecs/features/exclusive_builds.prf:
../mkspecs/features/default_pre.prf:
../.qmake.cache:
../mkspecs/qconfig.pri:
../mkspecs/features/qt_functions.prf:
../mkspecs/features/qt_config.prf:
../mkspecs/features/release.prf:
../mkspecs/features/default_post.prf:
../mkspecs/features/unix/dylib.prf:
../mkspecs/features/unix/largefile.prf:
../mkspecs/features/dll.prf:
../mkspecs/features/shared.prf:
../mkspecs/features/silent.prf:
../mkspecs/features/warn_on.prf:
../mkspecs/features/qt.prf:
../mkspecs/features/unix/thread.prf:
../mkspecs/features/moc.prf:
../mkspecs/features/resources.prf:
../mkspecs/features/uic.prf:
../mkspecs/features/yacc.prf:
../mkspecs/features/lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ../mkspecs/qws/linux-arm-g++ -o Makefile examples.pro

qmake_all: sub-network-qmake_all sub-statemachine-qmake_all sub-threads-qmake_all sub-xml-qmake_all sub-animation-qmake_all sub-desktop-qmake_all sub-dialogs-qmake_all sub-draganddrop-qmake_all sub-effects-qmake_all sub-graphicsview-qmake_all sub-ipc-qmake_all sub-itemviews-qmake_all sub-layouts-qmake_all sub-linguist-qmake_all sub-mainwindows-qmake_all sub-painting-qmake_all sub-richtext-qmake_all sub-sql-qmake_all sub-tools-qmake_all sub-tutorials-qmake_all sub-widgets-qmake_all sub-uitools-qmake_all sub-touch-qmake_all sub-gestures-qmake_all sub-script-qmake_all sub-qws-qmake_all sub-declarative-qmake_all FORCE

make_default: sub-network-make_default sub-statemachine-make_default sub-threads-make_default sub-xml-make_default sub-animation-make_default sub-desktop-make_default sub-dialogs-make_default sub-draganddrop-make_default sub-effects-make_default sub-graphicsview-make_default sub-ipc-make_default sub-itemviews-make_default sub-layouts-make_default sub-linguist-make_default sub-mainwindows-make_default sub-painting-make_default sub-richtext-make_default sub-sql-make_default sub-tools-make_default sub-tutorials-make_default sub-widgets-make_default sub-uitools-make_default sub-touch-make_default sub-gestures-make_default sub-script-make_default sub-qws-make_default sub-declarative-make_default FORCE
make_first: sub-network-make_first sub-statemachine-make_first sub-threads-make_first sub-xml-make_first sub-animation-make_first sub-desktop-make_first sub-dialogs-make_first sub-draganddrop-make_first sub-effects-make_first sub-graphicsview-make_first sub-ipc-make_first sub-itemviews-make_first sub-layouts-make_first sub-linguist-make_first sub-mainwindows-make_first sub-painting-make_first sub-richtext-make_first sub-sql-make_first sub-tools-make_first sub-tutorials-make_first sub-widgets-make_first sub-uitools-make_first sub-touch-make_first sub-gestures-make_first sub-script-make_first sub-qws-make_first sub-declarative-make_first FORCE
all: sub-network-all sub-statemachine-all sub-threads-all sub-xml-all sub-animation-all sub-desktop-all sub-dialogs-all sub-draganddrop-all sub-effects-all sub-graphicsview-all sub-ipc-all sub-itemviews-all sub-layouts-all sub-linguist-all sub-mainwindows-all sub-painting-all sub-richtext-all sub-sql-all sub-tools-all sub-tutorials-all sub-widgets-all sub-uitools-all sub-touch-all sub-gestures-all sub-script-all sub-qws-all sub-declarative-all FORCE
clean: sub-network-clean sub-statemachine-clean sub-threads-clean sub-xml-clean sub-animation-clean sub-desktop-clean sub-dialogs-clean sub-draganddrop-clean sub-effects-clean sub-graphicsview-clean sub-ipc-clean sub-itemviews-clean sub-layouts-clean sub-linguist-clean sub-mainwindows-clean sub-painting-clean sub-richtext-clean sub-sql-clean sub-tools-clean sub-tutorials-clean sub-widgets-clean sub-uitools-clean sub-touch-clean sub-gestures-clean sub-script-clean sub-qws-clean sub-declarative-clean FORCE
distclean: sub-network-distclean sub-statemachine-distclean sub-threads-distclean sub-xml-distclean sub-animation-distclean sub-desktop-distclean sub-dialogs-distclean sub-draganddrop-distclean sub-effects-distclean sub-graphicsview-distclean sub-ipc-distclean sub-itemviews-distclean sub-layouts-distclean sub-linguist-distclean sub-mainwindows-distclean sub-painting-distclean sub-richtext-distclean sub-sql-distclean sub-tools-distclean sub-tutorials-distclean sub-widgets-distclean sub-uitools-distclean sub-touch-distclean sub-gestures-distclean sub-script-distclean sub-qws-distclean sub-declarative-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-network-install_subtargets sub-statemachine-install_subtargets sub-threads-install_subtargets sub-xml-install_subtargets sub-animation-install_subtargets sub-desktop-install_subtargets sub-dialogs-install_subtargets sub-draganddrop-install_subtargets sub-effects-install_subtargets sub-graphicsview-install_subtargets sub-ipc-install_subtargets sub-itemviews-install_subtargets sub-layouts-install_subtargets sub-linguist-install_subtargets sub-mainwindows-install_subtargets sub-painting-install_subtargets sub-richtext-install_subtargets sub-sql-install_subtargets sub-tools-install_subtargets sub-tutorials-install_subtargets sub-widgets-install_subtargets sub-uitools-install_subtargets sub-touch-install_subtargets sub-gestures-install_subtargets sub-script-install_subtargets sub-qws-install_subtargets sub-declarative-install_subtargets FORCE
uninstall_subtargets: sub-network-uninstall_subtargets sub-statemachine-uninstall_subtargets sub-threads-uninstall_subtargets sub-xml-uninstall_subtargets sub-animation-uninstall_subtargets sub-desktop-uninstall_subtargets sub-dialogs-uninstall_subtargets sub-draganddrop-uninstall_subtargets sub-effects-uninstall_subtargets sub-graphicsview-uninstall_subtargets sub-ipc-uninstall_subtargets sub-itemviews-uninstall_subtargets sub-layouts-uninstall_subtargets sub-linguist-uninstall_subtargets sub-mainwindows-uninstall_subtargets sub-painting-uninstall_subtargets sub-richtext-uninstall_subtargets sub-sql-uninstall_subtargets sub-tools-uninstall_subtargets sub-tutorials-uninstall_subtargets sub-widgets-uninstall_subtargets sub-uitools-uninstall_subtargets sub-touch-uninstall_subtargets sub-gestures-uninstall_subtargets sub-script-uninstall_subtargets sub-qws-uninstall_subtargets sub-declarative-uninstall_subtargets FORCE

sub-network-check: network/$(MAKEFILE)
	cd network/ && $(MAKE) check
sub-statemachine-check: statemachine/$(MAKEFILE)
	cd statemachine/ && $(MAKE) check
sub-threads-check: threads/$(MAKEFILE)
	cd threads/ && $(MAKE) check
sub-xml-check: xml/$(MAKEFILE)
	cd xml/ && $(MAKE) check
sub-animation-check: animation/$(MAKEFILE)
	cd animation/ && $(MAKE) check
sub-desktop-check: desktop/$(MAKEFILE)
	cd desktop/ && $(MAKE) check
sub-dialogs-check: dialogs/$(MAKEFILE)
	cd dialogs/ && $(MAKE) check
sub-draganddrop-check: draganddrop/$(MAKEFILE)
	cd draganddrop/ && $(MAKE) check
sub-effects-check: effects/$(MAKEFILE)
	cd effects/ && $(MAKE) check
sub-graphicsview-check: graphicsview/$(MAKEFILE)
	cd graphicsview/ && $(MAKE) check
sub-ipc-check: ipc/$(MAKEFILE)
	cd ipc/ && $(MAKE) check
sub-itemviews-check: itemviews/$(MAKEFILE)
	cd itemviews/ && $(MAKE) check
sub-layouts-check: layouts/$(MAKEFILE)
	cd layouts/ && $(MAKE) check
sub-linguist-check: linguist/$(MAKEFILE)
	cd linguist/ && $(MAKE) check
sub-mainwindows-check: mainwindows/$(MAKEFILE)
	cd mainwindows/ && $(MAKE) check
sub-painting-check: painting/$(MAKEFILE)
	cd painting/ && $(MAKE) check
sub-richtext-check: richtext/$(MAKEFILE)
	cd richtext/ && $(MAKE) check
sub-sql-check: sql/$(MAKEFILE)
	cd sql/ && $(MAKE) check
sub-tools-check: tools/$(MAKEFILE)
	cd tools/ && $(MAKE) check
sub-tutorials-check: tutorials/$(MAKEFILE)
	cd tutorials/ && $(MAKE) check
sub-widgets-check: widgets/$(MAKEFILE)
	cd widgets/ && $(MAKE) check
sub-uitools-check: uitools/$(MAKEFILE)
	cd uitools/ && $(MAKE) check
sub-touch-check: touch/$(MAKEFILE)
	cd touch/ && $(MAKE) check
sub-gestures-check: gestures/$(MAKEFILE)
	cd gestures/ && $(MAKE) check
sub-script-check: script/$(MAKEFILE)
	cd script/ && $(MAKE) check
sub-qws-check: qws/$(MAKEFILE)
	cd qws/ && $(MAKE) check
sub-declarative-check: declarative/$(MAKEFILE)
	cd declarative/ && $(MAKE) check
check: sub-network-check sub-statemachine-check sub-threads-check sub-xml-check sub-animation-check sub-desktop-check sub-dialogs-check sub-draganddrop-check sub-effects-check sub-graphicsview-check sub-ipc-check sub-itemviews-check sub-layouts-check sub-linguist-check sub-mainwindows-check sub-painting-check sub-richtext-check sub-sql-check sub-tools-check sub-tutorials-check sub-widgets-check sub-uitools-check sub-touch-check sub-gestures-check sub-script-check sub-qws-check sub-declarative-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install_sources: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/target/usr/share/qt/examples/ || $(MKDIR) $(INSTALL_ROOT)/mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/target/usr/share/qt/examples/ 
	-$(INSTALL_FILE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/README $(INSTALL_ROOT)/mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/target/usr/share/qt/examples/
	-$(INSTALL_FILE) /mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/build/qt-everywhere-opensource-src-4.7.1/examples/examples.pro $(INSTALL_ROOT)/mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/target/usr/share/qt/examples/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/target/usr/share/qt/examples/README 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/target/usr/share/qt/examples/examples.pro
	-$(DEL_DIR) $(INSTALL_ROOT)/mnt/local_git/tar_bakup/qtmoko/linux/buildroot/output/target/usr/share/qt/examples/ 


install: install_subtargets install_sources  FORCE

uninstall: uninstall_sources  uninstall_subtargets FORCE

FORCE:

